name: kutuku
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cereal
      fonts:
        - asset: assets/fonts/Airbnb Cereal-fontiko/AirbnbCereal_W_Lt.otf
          weight: 300
        - asset: assets/fonts/Airbnb Cereal-fontiko/AirbnbCereal_W_Bk.otf
          weight: 400
        - asset: assets/fonts/Airbnb Cereal-fontiko/AirbnbCereal_W_Md.otf
          weight: 500
        - asset: assets/fonts/Airbnb Cereal-fontiko/AirbnbCereal_W_Bd.otf
          weight: 700
        - asset: assets/fonts/Airbnb Cereal-fontiko/AirbnbCereal_W_XBd.otf
          weight: 800
